name: zentra
description: "A self-hosted, decentralized file browsing experience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.13.0
  auto_route: ^10.1.0+1
  collection: ^1.19.1
  cronet_http: ^1.3.4
  cupertino_http: ^2.2.0
  dart_mappable: ^4.5.0
  fetch_client: ^1.1.4
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  http: ^1.4.0
  intl: ^0.20.2
  logging: ^1.3.0
  mime: ^2.0.0
  path: ^1.9.1
  flutter_animate: ^4.5.2
  skeletonizer: ^2.0.1
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.5.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15
  mockito: ^5.4.6
  bloc_test: ^10.0.0
  injectable_generator: ^2.7.0

flutter:
  generate: true
  uses-material-design: false
